### ISSUE TITLE
Document data_gen.py

### ISSUE THREAD

**Issue by AnsahMohammad** [AnsahMohammad/gesture-scroll#5]
Write documentation for the Data Generator `data_gen.py`

**Comment by Donoven-Lam** [comment]
Hey, can you tell me what kind of documentation you specifically want for data_gen.py? Is it more so how the code itself works?

**Comment by AnsahMohammad** [comment]
Hey @Donoven-Lam 
Yeah Just add a small documentation which describes what the generator code does and 
Instructions on how to capture images and save them

**Comment by AnsahMohammad** [comment]
@Donoven-Lam Are you interested in working on this Issue?

**Comment by Donoven-Lam** [comment]
Yes, @AnsahMohammad I'm still interested in working on this issue. I'll try to get it done by tonight/tomorrow. Apologies for the delay.
